
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.Notebook notebook1;
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Entry entry5;
	private global::Gtk.Button button16;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Button button2;
	private global::Gtk.Button button3;
	private global::Gtk.Button button4;
	private global::Gtk.Button button5;
	private global::Gtk.Button button6;
	private global::Gtk.Button button7;
	private global::Gtk.Button button8;
	private global::Gtk.Button button9;
	private global::Gtk.Button button10;
	private global::Gtk.Button button11;
	private global::Gtk.Button button15;
	private global::Gtk.Button button12;
	private global::Gtk.Button button18;
	private global::Gtk.Button button17;
	private global::Gtk.Button button19;
	private global::Gtk.Button button20;
	private global::Gtk.Button button21;
	private global::Gtk.Label label1;
	private global::Gtk.DrawingArea drawingarea2;
	private global::Gtk.Label label2;
	private global::Gtk.Fixed fixed3;
	private global::Gtk.Entry entry3;
	private global::Gtk.Label label7;
	private global::Gtk.Button button13;
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	private global::Gtk.TextView textview2;
	private global::Gtk.Entry entry4;
	private global::Gtk.Label label8;
	private global::Gtk.Button button14;
	private global::Gtk.Label label4;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView textview1;
	private global::Gtk.Label label6;
	private global::Gtk.Statusbar statusbar101;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = "MainWindow";
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.notebook1 = new global::Gtk.Notebook ();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 1;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entry5 = new global::Gtk.Entry ();
		this.entry5.CanFocus = true;
		this.entry5.Name = "entry5";
		this.entry5.IsEditable = true;
		this.entry5.InvisibleChar = '•';
		this.fixed1.Add (this.entry5);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry5]));
		w1.X = 36;
		w1.Y = 383;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button16 = new global::Gtk.Button ();
		this.button16.CanFocus = true;
		this.button16.Name = "button16";
		this.button16.UseUnderline = true;
		this.button16.Label = "Send text";
		this.fixed1.Add (this.button16);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button16]));
		w2.X = 201;
		w2.Y = 380;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.WidthRequest = 250;
		this.hbox1.HeightRequest = 45;
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button2 = new global::Gtk.Button ();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = "1";
		this.hbox1.Add (this.button2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button2]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button3 = new global::Gtk.Button ();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = "2";
		this.hbox1.Add (this.button3);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button3]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button4 = new global::Gtk.Button ();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = "3";
		this.hbox1.Add (this.button4);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button4]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button5 = new global::Gtk.Button ();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = "4";
		this.hbox1.Add (this.button5);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button5]));
		w6.Position = 3;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button6 = new global::Gtk.Button ();
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.Label = "5";
		this.hbox1.Add (this.button6);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button6]));
		w7.Position = 4;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button7 = new global::Gtk.Button ();
		this.button7.CanFocus = true;
		this.button7.Name = "button7";
		this.button7.UseUnderline = true;
		this.button7.Label = "6";
		this.hbox1.Add (this.button7);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button7]));
		w8.Position = 5;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button8 = new global::Gtk.Button ();
		this.button8.CanFocus = true;
		this.button8.Name = "button8";
		this.button8.UseUnderline = true;
		this.button8.Label = "7";
		this.hbox1.Add (this.button8);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button8]));
		w9.Position = 6;
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button9 = new global::Gtk.Button ();
		this.button9.CanFocus = true;
		this.button9.Name = "button9";
		this.button9.UseUnderline = true;
		this.button9.Label = "8";
		this.hbox1.Add (this.button9);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button9]));
		w10.Position = 7;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button10 = new global::Gtk.Button ();
		this.button10.CanFocus = true;
		this.button10.Name = "button10";
		this.button10.UseUnderline = true;
		this.button10.Label = "9";
		this.hbox1.Add (this.button10);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button10]));
		w11.Position = 8;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button11 = new global::Gtk.Button ();
		this.button11.CanFocus = true;
		this.button11.Name = "button11";
		this.button11.UseUnderline = true;
		this.button11.Label = "0";
		this.hbox1.Add (this.button11);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button11]));
		w12.Position = 9;
		w12.Expand = false;
		w12.Fill = false;
		this.fixed1.Add (this.hbox1);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.hbox1]));
		w13.X = 43;
		w13.Y = 27;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button15 = new global::Gtk.Button ();
		this.button15.WidthRequest = 100;
		this.button15.CanFocus = true;
		this.button15.Name = "button15";
		this.button15.UseUnderline = true;
		this.button15.Label = "Move Down";
		this.fixed1.Add (this.button15);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button15]));
		w14.X = 107;
		w14.Y = 263;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button12 = new global::Gtk.Button ();
		this.button12.WidthRequest = 100;
		this.button12.CanFocus = true;
		this.button12.Name = "button12";
		this.button12.UseUnderline = true;
		this.button12.Label = "Move Up";
		this.fixed1.Add (this.button12);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button12]));
		w15.X = 107;
		w15.Y = 156;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button18 = new global::Gtk.Button ();
		this.button18.HeightRequest = 100;
		this.button18.CanFocus = true;
		this.button18.Name = "button18";
		this.button18.UseUnderline = true;
		this.button18.Label = "<";
		this.fixed1.Add (this.button18);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button18]));
		w16.X = 77;
		w16.Y = 173;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button17 = new global::Gtk.Button ();
		this.button17.WidthRequest = 50;
		this.button17.HeightRequest = 50;
		this.button17.CanFocus = true;
		this.button17.Name = "button17";
		this.button17.UseUnderline = true;
		this.button17.Label = "o";
		this.fixed1.Add (this.button17);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button17]));
		w17.X = 133;
		w17.Y = 197;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button19 = new global::Gtk.Button ();
		this.button19.HeightRequest = 100;
		this.button19.CanFocus = true;
		this.button19.Name = "button19";
		this.button19.UseUnderline = true;
		this.button19.Label = ">";
		this.fixed1.Add (this.button19);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button19]));
		w18.X = 217;
		w18.Y = 176;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button20 = new global::Gtk.Button ();
		this.button20.CanFocus = true;
		this.button20.Name = "button20";
		this.button20.UseUnderline = true;
		this.button20.Label = "Vol.Up";
		this.fixed1.Add (this.button20);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button20]));
		w19.X = 26;
		w19.Y = 297;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button21 = new global::Gtk.Button ();
		this.button21.CanFocus = true;
		this.button21.Name = "button21";
		this.button21.UseUnderline = true;
		this.button21.Label = "Vol.Dn";
		this.fixed1.Add (this.button21);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button21]));
		w20.X = 25;
		w20.Y = 327;
		this.notebook1.Add (this.fixed1);
		// Notebook tab
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = "KeyMode";
		this.notebook1.SetTabLabel (this.fixed1, this.label1);
		this.label1.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.drawingarea2 = new global::Gtk.DrawingArea ();
		this.drawingarea2.Name = "drawingarea2";
		this.notebook1.Add (this.drawingarea2);
		global::Gtk.Notebook.NotebookChild w22 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.drawingarea2]));
		w22.Position = 1;
		// Notebook tab
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = "Touchpad";
		this.notebook1.SetTabLabel (this.drawingarea2, this.label2);
		this.label2.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.fixed3 = new global::Gtk.Fixed ();
		this.fixed3.Name = "fixed3";
		this.fixed3.HasWindow = false;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.entry3 = new global::Gtk.Entry ();
		this.entry3.CanFocus = true;
		this.entry3.Name = "entry3";
		this.entry3.Text = "192.168.1.65";
		this.entry3.IsEditable = true;
		this.entry3.InvisibleChar = '•';
		this.fixed3.Add (this.entry3);
		global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.entry3]));
		w23.X = 40;
		w23.Y = 19;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = "TV IP";
		this.fixed3.Add (this.label7);
		global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.label7]));
		w24.X = 214;
		w24.Y = 20;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.button13 = new global::Gtk.Button ();
		this.button13.CanFocus = true;
		this.button13.Name = "button13";
		this.button13.UseUnderline = true;
		this.button13.Label = "Auth";
		this.fixed3.Add (this.button13);
		global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.button13]));
		w25.X = 261;
		w25.Y = 18;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.WidthRequest = 250;
		this.GtkScrolledWindow1.HeightRequest = 150;
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.VscrollbarPolicy = ((global::Gtk.PolicyType)(0));
		this.GtkScrolledWindow1.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.textview2 = new global::Gtk.TextView ();
		this.textview2.Buffer.Text = "Enter the ip of tv and press AUTH btn.";
		this.textview2.CanFocus = true;
		this.textview2.Name = "textview2";
		this.textview2.WrapMode = ((global::Gtk.WrapMode)(2));
		this.GtkScrolledWindow1.Add (this.textview2);
		this.fixed3.Add (this.GtkScrolledWindow1);
		global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.GtkScrolledWindow1]));
		w27.X = 39;
		w27.Y = 300;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.entry4 = new global::Gtk.Entry ();
		this.entry4.CanFocus = true;
		this.entry4.Name = "entry4";
		this.entry4.Text = "DDRVTF";
		this.entry4.IsEditable = true;
		this.entry4.InvisibleChar = '•';
		this.fixed3.Add (this.entry4);
		global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.entry4]));
		w28.X = 40;
		w28.Y = 54;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = "PairCode";
		this.fixed3.Add (this.label8);
		global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.label8]));
		w29.X = 204;
		w29.Y = 56;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.button14 = new global::Gtk.Button ();
		this.button14.CanFocus = true;
		this.button14.Name = "button14";
		this.button14.UseUnderline = true;
		this.button14.Label = "Pair";
		this.fixed3.Add (this.button14);
		global::Gtk.Fixed.FixedChild w30 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.button14]));
		w30.X = 262;
		w30.Y = 49;
		this.notebook1.Add (this.fixed3);
		global::Gtk.Notebook.NotebookChild w31 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.fixed3]));
		w31.Position = 2;
		// Notebook tab
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = "Settings";
		this.notebook1.SetTabLabel (this.fixed3, this.label4);
		this.label4.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textview1 = new global::Gtk.TextView ();
		this.textview1.CanFocus = true;
		this.textview1.Name = "textview1";
		this.GtkScrolledWindow.Add (this.textview1);
		this.notebook1.Add (this.GtkScrolledWindow);
		global::Gtk.Notebook.NotebookChild w33 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.GtkScrolledWindow]));
		w33.Position = 3;
		// Notebook tab
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = "Log";
		this.notebook1.SetTabLabel (this.GtkScrolledWindow, this.label6);
		this.label6.ShowAll ();
		this.vbox1.Add (this.notebook1);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.notebook1]));
		w34.Position = 0;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusbar101 = new global::Gtk.Statusbar ();
		this.statusbar101.Name = "statusbar101";
		this.statusbar101.Spacing = 6;
		this.vbox1.Add (this.statusbar101);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar101]));
		w35.Position = 1;
		w35.Expand = false;
		w35.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 658;
		this.DefaultHeight = 504;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.notebook1.SwitchPage += new global::Gtk.SwitchPageHandler (this.OnNotebook1SwitchPage);
		this.button3.Clicked += new global::System.EventHandler (this.OnButton3Clicked);
		this.button4.Clicked += new global::System.EventHandler (this.OnButton4Clicked);
		this.button5.Clicked += new global::System.EventHandler (this.OnButton5Clicked);
		this.button6.Clicked += new global::System.EventHandler (this.OnButton6Clicked);
		this.button7.Clicked += new global::System.EventHandler (this.OnButton7Clicked);
		this.button8.Clicked += new global::System.EventHandler (this.OnButton8Clicked);
		this.button9.Clicked += new global::System.EventHandler (this.OnButton9Clicked);
		this.button10.Clicked += new global::System.EventHandler (this.OnButton10Clicked);
		this.button11.Clicked += new global::System.EventHandler (this.OnButton11Clicked);
		this.button13.Clicked += new global::System.EventHandler (this.OnButton13Clicked);
		this.button14.Clicked += new global::System.EventHandler (this.OnButton14Clicked);
	}
}
